### ISSUE TITLE
Unclear why server is not registering

### ISSUE THREAD

**Issue by jpds** [matrix-org/pantalaimon#54]
I've configured pantalaimon as follows:

```
[company-matrix]
Homeserver = https://company.modular.im
ListenAddress = 0.0.0.0
ListenPort = 8008
SSL = True
UseKeyring = False
IgnoreVerification = True
```

I've then taken a https://github.com/matrix-org/go-neb bot and pointed it at pantalaimon:

```
clients:                                                                                                                                   
  - UserID: "@bot:company.org"                                                                                                         
    AccessToken: "blab"                                                                                            
    HomeserverURL: "http://pantalaimon:8008"
    Sync: true                                                                                                                             
    AutoJoinRooms: true                                                                                                                    
    DisplayName: "bot"
```

...but then I see:

```
panctl> list-servers
pantalaimon servers:
```

And in the pantalaimon logs:

```
WARNING: pantalaimon: User @bot:company.org doesn't have a matching pan client.
```

The bot can connect to the Matrix server fine without pantalaimon.
